package com.example.BacK.application.g_Stock.Command.mouvementStock.entreeStock;

import com.example.BacK.application.interfaces.g_Stock.article.IArticleRepositoryService;
import com.example.BacK.application.interfaces.g_Stock.entrepot.IEntrepotRepositoryService;
import com.example.BacK.application.interfaces.g_Stock.mouvementStock.IMouvementStockRepositoryService;
import com.example.BacK.application.interfaces.g_Stock.stock.IStockRepositoryService;
import com.example.BacK.application.interfaces.g_Stock.stockLot.IStockLotRepositoryService;
import com.example.BacK.application.interfaces.g_Stock.stockLotMouvement.IStockLotMouvementRepositoryService;
import com.example.BacK.application.mediator.RequestHandler;
import com.example.BacK.domain.g_Stock.Article;
import com.example.BacK.domain.g_Stock.Entrepot;
import com.example.BacK.domain.g_Stock.MouvementStock;
import com.example.BacK.domain.g_Stock.Stock;
import com.example.BacK.domain.g_Stock.StockLot;
import com.example.BacK.domain.g_Stock.StockLotMouvement;
import com.example.BacK.domain.g_Stock.enumEntity.TypeMouvement;
import com.example.BacK.domain.g_Utilisateurs.User;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;

@Component("EntreeStockHandler")
public class EntreeStockHandler implements RequestHandler<EntreeStockCommand, EntreeStockResponse> {

    private final IMouvementStockRepositoryService mouvementStockRepositoryService;
    private final IArticleRepositoryService articleRepositoryService;
    private final IEntrepotRepositoryService entrepotRepositoryService;
    private final IStockRepositoryService stockRepositoryService;
    private final IStockLotRepositoryService stockLotRepositoryService;
    private final IStockLotMouvementRepositoryService stockLotMouvementRepositoryService;
    private final EntreeStockValidator validator;

    public EntreeStockHandler(
            IMouvementStockRepositoryService mouvementStockRepositoryService,
            IArticleRepositoryService articleRepositoryService,
            IEntrepotRepositoryService entrepotRepositoryService,
            IStockRepositoryService stockRepositoryService,
            IStockLotRepositoryService stockLotRepositoryService,
            IStockLotMouvementRepositoryService stockLotMouvementRepositoryService,
            EntreeStockValidator validator) {
        this.mouvementStockRepositoryService = mouvementStockRepositoryService;
        this.articleRepositoryService = articleRepositoryService;
        this.entrepotRepositoryService = entrepotRepositoryService;
        this.stockRepositoryService = stockRepositoryService;
        this.stockLotRepositoryService = stockLotRepositoryService;
        this.stockLotMouvementRepositoryService = stockLotMouvementRepositoryService;
        this.validator = validator;
    }

    @Override
    public EntreeStockResponse handle(EntreeStockCommand command) {
        // Validate command
        validator.validate(command);

        // Get authenticated user
        String currentUserId = getCurrentUserId();

        // Create mouvement stock
        MouvementStock mouvementStock = new MouvementStock();
        // ID will be auto-generated by JPA @GeneratedValue
        mouvementStock.setTypeMouvement(TypeMouvement.ENTREE);
        mouvementStock.setTypeEntree(command.getTypeEntree());
        
        // Set article
        Article article = articleRepositoryService.getById(command.getArticleId());
        mouvementStock.setArticle(article);
        
        // Set destination warehouse (for entry, only destination is set)
        Entrepot destinationEntrepot = entrepotRepositoryService.getById(command.getDestinationEntrepotId());
        mouvementStock.setDestinationEntrepot(destinationEntrepot);
        mouvementStock.setSourceEntrepot(null); // No source for incoming stock
        
        // Set quantity and date
        mouvementStock.setQuantite(command.getQuantite().doubleValue());
        LocalDateTime dateMouvement = command.getDateMouvement() != null ? 
            command.getDateMouvement().atStartOfDay() : LocalDateTime.now();
        mouvementStock.setDateMouvement(dateMouvement);
        
        // Set user
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null && authentication.getPrincipal() instanceof User) {
            User currentUser = (User) authentication.getPrincipal();
            mouvementStock.setUtilisateur(currentUser);
        }
        
        // Set references and batch information
        mouvementStock.setReference(command.getReference());
        mouvementStock.setNumeroBonReception(command.getNumeroBonReception());
        mouvementStock.setReferenceBonCommande(command.getReferenceBonCommande());
        mouvementStock.setPrixAchatUnitaire(command.getPrixAchatUnitaire());
        mouvementStock.setPrixVenteUnitaire(command.getPrixVenteUnitaire());
        mouvementStock.setFactureUrl(command.getFactureUrl());
        mouvementStock.setNumeroFacture(command.getNumeroFacture());
        mouvementStock.setStatut(command.getStatut());
        mouvementStock.setNotes(command.getNotes());
        mouvementStock.setCreatedBy(currentUserId);
        mouvementStock.setUpdatedBy(currentUserId);
        
        // Determine whether to add to existing lot or create new one
        StockLot stockLot;
        if (command.getStockLotId() != null && !command.getStockLotId().isEmpty()) {
            // Add to existing lot
            stockLot = stockLotRepositoryService.getById(command.getStockLotId());
            if (stockLot == null) {
                throw new IllegalArgumentException("Le lot spécifié n'existe pas: " + command.getStockLotId());
            }
            
            // Update lot quantity
            int newQuantity = stockLot.getQuantiteActuelle() + command.getQuantite();
            stockLot.setQuantiteActuelle(newQuantity);
            stockLot.setUpdatedBy(currentUserId);
            
            // Optionally update invoice if new one is provided
            if (command.getFactureUrl() != null) {
                stockLot.setFactureUrl(command.getFactureUrl());
            }
            if (command.getNumeroFacture() != null) {
                stockLot.setNumeroFacture(command.getNumeroFacture());
            }
            
            stockLot = stockLotRepositoryService.update(stockLot);
        } else {
            // Create new stock batch (lot)
            stockLot = createStockLot(command, article, destinationEntrepot, currentUserId);
            stockLot = stockLotRepositoryService.add(stockLot);
        }
        
        // Link the stock lot to the mouvement BEFORE saving
        mouvementStock.setStockLotId(stockLot.getId());
        
        // Save mouvement (with stockLotId already set)
        MouvementStock savedMouvement = mouvementStockRepositoryService.add(mouvementStock);
        
        // Create batch movement record for tracking
        createStockLotMouvement(stockLot, savedMouvement, command.getQuantite(), currentUserId);
        
        // Update global stock levels
        updateStockLevels(command.getArticleId(), command.getDestinationEntrepotId(), command.getQuantite());
        
        return new EntreeStockResponse(savedMouvement.getId());
    }

    private StockLot createStockLot(EntreeStockCommand command, Article article, Entrepot entrepot, String userId) {
        StockLot stockLot = new StockLot();
        stockLot.setArticle(article);
        stockLot.setEntrepot(entrepot);
        
        // Set batch number (auto-generated if not provided)
        if (command.getNumeroLot() != null && !command.getNumeroLot().isEmpty()) {
            stockLot.setNumeroLot(command.getNumeroLot());
        }
        // NumeroLot will be auto-generated in @PrePersist if not set
        
        // Set quantities
        stockLot.setQuantiteInitiale(command.getQuantite());
        stockLot.setQuantiteActuelle(command.getQuantite());
        stockLot.setQuantiteReservee(0);
        
        // Set dates
        stockLot.setDateAchat(command.getDateAchat() != null ? command.getDateAchat() : 
            (command.getDateMouvement() != null ? command.getDateMouvement() : java.time.LocalDate.now()));
        stockLot.setDateExpiration(command.getDateExpiration());
        
        // Set pricing
        stockLot.setPrixAchatUnitaire(command.getPrixAchatUnitaire());
        stockLot.setPrixVenteUnitaire(command.getPrixVenteUnitaire());
        
        // Set invoice information
        stockLot.setFactureUrl(command.getFactureUrl());
        stockLot.setNumeroFacture(command.getNumeroFacture());
        stockLot.setReferenceFournisseur(command.getReferenceBonCommande());
        
        // Set notes and status
        stockLot.setNotes(command.getNotes());
        stockLot.setEstActif(true);
        stockLot.setCreatedBy(userId);
        stockLot.setUpdatedBy(userId);
        
        return stockLot;
    }

    private void createStockLotMouvement(StockLot stockLot, MouvementStock mouvementStock, Integer quantite, String userId) {
        StockLotMouvement stockLotMouvement = new StockLotMouvement();
        stockLotMouvement.setStockLot(stockLot);
        stockLotMouvement.setMouvementStock(mouvementStock);
        stockLotMouvement.setTypeMouvement(TypeMouvement.ENTREE);
        stockLotMouvement.setQuantite(quantite);
        stockLotMouvement.setQuantiteAvant(0);
        stockLotMouvement.setQuantiteApres(quantite);
        stockLotMouvement.setPrixUnitaire(stockLot.getPrixAchatUnitaire());
        stockLotMouvement.setValeurTotale(quantite * stockLot.getPrixAchatUnitaire());
        stockLotMouvement.setDateMouvement(mouvementStock.getDateMouvement());
        stockLotMouvement.setUtilisateur(mouvementStock.getUtilisateur());
        stockLotMouvement.setReference(mouvementStock.getReference());
        stockLotMouvement.setCreatedBy(userId);
        stockLotMouvement.setUpdatedBy(userId);
        
        stockLotMouvementRepositoryService.add(stockLotMouvement);
    }

    private String getCurrentUserId() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null && authentication.getPrincipal() instanceof User) {
            User currentUser = (User) authentication.getPrincipal();
            return currentUser.getId();
        }
        return "SYSTEM";
    }

    private void updateStockLevels(String articleId, String entrepotId, Integer quantite) {
        Stock stock = stockRepositoryService.findByArticleIdAndEntrepotId(articleId, entrepotId);
        
        if (stock == null) {
            // Create new stock record
            stock = new Stock();
            // Don't manually set ID - let JPA generate it
            
            Article article = new Article();
            article.setId(articleId);
            stock.setArticle(article);
            
            Entrepot entrepot = new Entrepot();
            entrepot.setId(entrepotId);
            stock.setEntrepot(entrepot);
            
            stock.setQuantite(quantite);
            
            stockRepositoryService.add(stock);
        } else {
            // Update existing stock
            int oldQuantity = stock.getQuantite();
            stock.setQuantite(stock.getQuantite() + quantite);
            stockRepositoryService.update(stock);
        }
    }
}
