package com.example.BacK.domain.g_Stock;

import com.example.BacK.domain.Auditable;
import com.example.BacK.domain.g_Stock.enumEntity.TypeMouvement;
import com.example.BacK.domain.g_Utilisateurs.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Tracks all movements (entries and exits) for a specific stock batch.
 * This provides complete traceability for each batch operation.
 */
@Entity
@Table(name = "STOCK_LOT_MOUVEMENT")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(callSuper = false)
public class StockLotMouvement extends Auditable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", length = 36)
    private String id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_lot_id", nullable = false)
    private StockLot stockLot;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mouvement_stock_id", nullable = false)
    private MouvementStock mouvementStock;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "type_mouvement", length = 20, nullable = false)
    private TypeMouvement typeMouvement;
    
    @Column(name = "quantite", nullable = false)
    private Integer quantite;
    
    @Column(name = "quantite_avant")
    private Integer quantiteAvant;
    
    @Column(name = "quantite_apres")
    private Integer quantiteApres;
    
    @Column(name = "prix_unitaire")
    private Double prixUnitaire;
    
    @Column(name = "valeur_totale")
    private Double valeurTotale;
    
    @Column(name = "date_mouvement", nullable = false)
    private LocalDateTime dateMouvement;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "utilisateur_id")
    private User utilisateur;
    
    @Column(name = "reference", length = 255)
    private String reference;
    
    @Column(name = "commentaire", columnDefinition = "TEXT")
    private String commentaire;
    
    @Column(name = "created_by", length = 36)
    private String createdBy;
    
    @Column(name = "updated_by", length = 36)
    private String updatedBy;
    
    @PrePersist
    protected void onCreate() {
        // ID will be auto-generated by JPA @GeneratedValue
        if (dateMouvement == null) {
            dateMouvement = LocalDateTime.now();
        }
        if (prixUnitaire != null && quantite != null) {
            valeurTotale = prixUnitaire * quantite;
        }
    }
}
